a=int(input("Enter runs scored by 1st batsman : "))
b=int(input("Enter runs scored by 2nd batsman : "))
c=int(input("Enter runs scored by 3rd batsman : "))
print("Strike rate of 1st batsman : ", a/60*100,"\nRun scored if they played 60 balls more : ", a*2,"\nMax no.of sixes they could have hit : ", a//6)
print("Strike rate of 2nd batsman : ", b/60*100,"\nRun scored if they played 60 balls more : ", b*2,"\nMax no.of sixes they could have hit : ", b//6)
print("Strike rate of 3rd batsman : ", c/60*100,"\nRun scored if they played 60 balls more : ", c*2,"\nMax no.of sixes they could have hit : ", c//6)