g=input("Enter Gender  : ")
b=input("Enter Branch  : ")
n=input("Enter Name    : ")
c=input("Enter College : ")
a=input("Enter Age     : ")
print("Name    : "+n+ "\nAge     : "+a+ "\nGender  : "+g+ "\nCollege : "+b+ "\nBranch   : "+c)
